# Equation we want to find (Lorentz)
## x' = -10x + 10y
## y' = 28x - y - xz
## z' = -2.67z + xy
## Lets, x0 = x, x1 = y, x2 = z

# Installing PySINDy



In [5]:
!pip install pysindy

# We had generated data for that equation, Loading the data

In [6]:
import numpy as np

data = np.loadtxt('lorenz_paper_medium.csv', delimiter=',' ,skiprows=1)
print(data[:10])

[[-8.          8.         27.        ]
 [-6.48640305  7.80317052 25.72552262]
 [-5.13801768  7.562589   24.60881074]
 [-3.94150621  7.31298837 23.6289285 ]
 [-2.88204816  7.07817171 22.76571068]
 [-1.94437992  6.87385318 22.00125009]
 [-1.11349145  6.70994837 21.3204598 ]
 [-0.37506514  6.59232752 20.71111451]
 [ 0.28427103  6.52411126 20.16363082]
 [ 0.87681948  6.50660382 19.67074273]]


# Deriving Lorentz Equation from data using SINDy

##Larger Threshold

In [7]:
import pysindy as ps

# Initialize the model
model = ps.SINDy(
    optimizer = ps.STLSQ(threshold=0.1), # threshold controls complexity of the generated equations
                                       # Larger the threshhold values -> more terms gets zeored -> smaller equations
    feature_library=ps.PolynomialLibrary(degree=3),
)

# Fit the model
model.fit(data, t=0.01) # t is the time step between measurements for the generated data

#Print Equations
model.print()

(x0)' = -9.979 x0 + 9.979 x1
(x1)' = 27.814 x0 + -0.965 x1 + -0.995 x0 x2
(x2)' = -2.659 x2 + 0.997 x0 x1


##Smaller Threshold

In [8]:
# Initialize the model
model = ps.SINDy(
    optimizer = ps.STLSQ(threshold=0), # threshold controls complexity of the generated equations
                                       # Smaller the threshhold values -> less terms gets zeored -> larger equations
    feature_library=ps.PolynomialLibrary(degree=3),
)

# Fit the model
model.fit(data, t=0.01) # t is the time step between measurements for the generated data

#Print Equations
model.print()

(x0)' = -0.014 1 + -10.129 x0 + 10.074 x1 + 0.003 x2 + 0.006 x0 x2 + -0.003 x1 x2
(x1)' = -0.088 1 + 28.397 x0 + -1.137 x1 + 0.019 x2 + 0.001 x0 x1 + -1.026 x0 x2 + 0.006 x1 x2 + -0.001 x2^2
(x2)' = -0.056 1 + 0.010 x0 + -0.016 x1 + -2.651 x2 + -0.016 x0^2 + 1.036 x0 x1 + -0.005 x0 x2 + -0.010 x1^2 + 0.004 x1 x2 + -0.001 x2^2 + -0.001 x0^3 + 0.001 x0^2 x1 + 0.001 x0^2 x2 + -0.001 x0 x1^2 + -0.001 x0 x1 x2
